import { Company } from "@/types";

export const BUILTIN_COMPANIES: Company[] = [
  {
    id: "amazon",
    name: "Amazon",
    ticker: "AMZN",
    priceMethod: "30day-trailing-avg",
    tranches: [
      { monthsFromGrant: 12, percentage: 5 },
      { monthsFromGrant: 24, percentage: 15 },
      { monthsFromGrant: 30, percentage: 20 },
      { monthsFromGrant: 36, percentage: 20 },
      { monthsFromGrant: 42, percentage: 20 },
      { monthsFromGrant: 48, percentage: 20 },
    ],
  },
  {
    id: "google",
    name: "Google",
    ticker: "GOOGL",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 18, percentage: 12.5 },
      { monthsFromGrant: 21, percentage: 6.25 },
      { monthsFromGrant: 24, percentage: 6.25 },
      { monthsFromGrant: 27, percentage: 6.25 },
      { monthsFromGrant: 30, percentage: 6.25 },
      { monthsFromGrant: 33, percentage: 6.25 },
      { monthsFromGrant: 36, percentage: 6.25 },
      { monthsFromGrant: 39, percentage: 6.25 },
      { monthsFromGrant: 42, percentage: 6.25 },
      { monthsFromGrant: 45, percentage: 6.25 },
      { monthsFromGrant: 48, percentage: 6.25 },
    ],
  },
  {
    id: "meta",
    name: "Meta",
    ticker: "META",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 24, percentage: 25 },
      { monthsFromGrant: 36, percentage: 25 },
      { monthsFromGrant: 48, percentage: 25 },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA",
    ticker: "NVDA",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 15, percentage: 6.25 },
      { monthsFromGrant: 18, percentage: 6.25 },
      { monthsFromGrant: 21, percentage: 6.25 },
      { monthsFromGrant: 24, percentage: 6.25 },
      { monthsFromGrant: 27, percentage: 6.25 },
      { monthsFromGrant: 30, percentage: 6.25 },
      { monthsFromGrant: 33, percentage: 6.25 },
      { monthsFromGrant: 36, percentage: 6.25 },
      { monthsFromGrant: 39, percentage: 6.25 },
      { monthsFromGrant: 42, percentage: 6.25 },
      { monthsFromGrant: 45, percentage: 6.25 },
      { monthsFromGrant: 48, percentage: 6.25 },
    ],
  },
  {
    id: "netflix",
    name: "Netflix",
    ticker: "NFLX",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 24, percentage: 25 },
      { monthsFromGrant: 36, percentage: 25 },
      { monthsFromGrant: 48, percentage: 25 },
    ],
  },
  {
    id: "microsoft",
    name: "Microsoft",
    ticker: "MSFT",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 24, percentage: 25 },
      { monthsFromGrant: 36, percentage: 25 },
      { monthsFromGrant: 48, percentage: 25 },
    ],
  },
  {
    id: "apple",
    name: "Apple",
    ticker: "AAPL",
    tranches: [
      { monthsFromGrant: 12, percentage: 25 },
      { monthsFromGrant: 24, percentage: 25 },
      { monthsFromGrant: 36, percentage: 25 },
      { monthsFromGrant: 48, percentage: 25 },
    ],
  },
];
